if (sanity.function.sanity_deduce_version.included)
	return ()
endif ()
set (sanity.function.sanity_deduce_version.included TRUE)

function (sanity_deduce_version given_version versions_list_name component_name outversion outindex)

	unset (${outversion} PARENT_SCOPE)
	unset (${outindex} PARENT_SCOPE)
        set(component_cache_version "sanity.component.version.${component_name}")
        set (need_set FALSE)
        if (NOT ${component_cache_version})
            set (need_set TRUE)
        endif ()

	sanity_back(${versions_list_name} latest_version)

	if ("${given_version}" STREQUAL "latest")
		set(version ${latest_version})
	elseif ("${given_version}" STREQUAL "any")
		if (${${component_cache_version}})
			set (version "${${component_cache_version}}")
		else ()
                    set (version ${latest_version})
		endif ()
	else ()
            if (NOT need_set)
                if ("${given_version}" VERSION_GREATER "${${component_cache_version}}")
                    message (FATAL_ERROR "sanity_deduce_version(${given_version}) requests version ${given_version} but version ${${component_cache_version}} already selected")
                else ()
                    set (version "${${component_cache_version}}")
                endif ()
            else ()
        	list (FIND ${versions_list_name} ${given_version} index)
        	if (${index} LESS 0)
                    if ("${given_version}" VERSION_LESS "${latest_version}")
                        set(version ${latest_version})
                    else ()
                        message (STATUS "${given_version} VERSION_LESS ${latest_version}")
                        message (FATAL_ERROR "sanity_deduce_version(${given_version}) - we don't have it")
                    endif ()
                else ()
                    set (version ${given_version})
                endif ()
            endif ()
	endif ()

       	list (FIND ${versions_list_name} ${version} index)
        if (need_set)
            set(${component_cache_version} ${version} CACHE STRING "version of component ${component_name}")
        endif ()
	set (${outversion} "${version}" PARENT_SCOPE)
	set (${outindex} "${index}" PARENT_SCOPE)

endfunction ()
